# Generated by Django 4.0.4 on 2022-04-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='status',
        ),
    ]
